### PR TITLE
name added

### PR DESCRIPTION
**Pull request by maddy020**
Issue:  31  

#### Short description of what this resolves:
This adds a list of contributors to the project

#### Changes proposed in this pull request and/or Screenshots of changes:

- Added my name in contributor.xml

### CODE REVIEW

**Comment by SuhailAhmadKhan** [comment]
please follow the PR template properly. Write Issue: 37

**Comment by maddy020** [comment]
> please follow the PR template properly. Write Issue: 31

Done

**Comment by SuhailAhmadKhan** [comment]
> > please follow the PR template properly. Write Issue: 31
> 
> Done

It is still not correct. It should be Issue: 31 instead of Issue: ISSUENUMBER

**Comment by SuhailAhmadKhan** [comment]
Issue: 31 not Issue: #31

**Pull request merged**
